apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image_flask.repository }}:{{ .Values.image_flask.tag }}"
          ports:
            - containerPort: 5001
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-space
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
