apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-flask
  namespace: infra-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-flask
  template:
    metadata:
      labels:
        app: infra-flask
    spec:
      containers:
        - name: infra-flask
          image: sivanmarom/infra_flask:infra_flask
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: infra-flask
  namespace: infra-space
spec:
  selector:
    app: infra-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
