global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['a9c5d77f0b641491e9c5ba9d073c6888-1693256622.us-west-2.elb.amazonaws.com']
  
  
  
