global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['ae150c7e7c6504e569c75e041d35b03c-485880012.us-west-2.elb.amazonaws.com']
  
  
  
