global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['a710fec2f50dc4e6eb2e9cc43c38e68b-1102740613.us-west-2.elb.amazonaws.com']
  
  
  
