global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['aebddd7946e22410abe8c6fed7dd4670-505242208.us-west-2.elb.amazonaws.com']
  
  
  
