apiVersion: v1
kind: Namespace
metadata:
  name: flask-space

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-flask
  namespace: flask-space
data:
  image-tag: PLACEHOLDER

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app
  namespace: flask-space
data:
  image-tag: PLACEHOLDER