apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app
  namespace: flask-space
data:
  image-tag: PLACEHOLDER_FLASK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ${PLACEHOLDER_FLASK}
          env:
            - name: PLACEHOLDER_FLASK
              valueFrom:
                configMapKeyRef:
                  name: flask-app
                  key: image-tag
          ports:
            - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-space
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer