"""empty message

Revision ID: 913cc5f0dc91
Revises: 
Create Date: 2023-06-29 14:28:10.367771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913cc5f0dc91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_profile')
    # ### end Alembic commands ###
